##################
# My Preferences #
##################

notify = true
flip_status_indicators = true

[keybindings]
# Song controls
## Fast forward / rewind
"b" = "seek -1000"
"f" = "seek +1000"
"B" = "seek -10000"
"F" = "seek +10000"

## Play / pause
"p" = "playpause"
"Enter" = "play"
"s" = "stop"

## Track manipulation
"H" = "previous"
"L" = "next"
"r" = "repeat"
"z" = "shuffle"
"D" = "delete"
"S" = "save"

## Open context menu
"O" = "open current"
"o" = "open selected"
"A" = "goto artist"
"a" = "goto album"

# Queue
## Add to queue
"E" = "queue"
"Ctrl+s" = "save queue"

## Move selected song up/down in the queue
"J" = "shift down 1"
"K" = "shift up 1"
"C" = "clear"

## Open the context menu for a Spotify link in the clipboard
"Ctrl+v" = "insert"

# Sound
"=" = "volup 1"
"-" = "voldown 1"
"[" = "voldown 5"
"]" = "volup 5"

# Movements
"F1" = "focus queue"
"F2" = "focus library"
"F3" = "focus search"
"F8" = "focus cover"

# Navigation
"Down" = "move down 1"
"G" = "move bottom"
"g" = "move top"
"Left" = "move left 1"
"Right" = "move right 1"
"Ctrl+d" = "move down 5"
"Ctrl+u" = "move up 5"
"Up" = "move up 1"
"h" = "move left 1"
"j" = "move down 1"
"k" = "move up 1"
"Ctrl+e" = "move down 1"
"Ctrl+y" = "move up 1"
"l" = "move right 1"
"." = "move playing"
"q" = "back"

# Sorting
"t" = "sort added d"
"T" = "sort title a"

# Sharing
"Y" = "share selected"
"y" = "share current"

# Other
"Q" = "quit"
"Z" = "quit"
"?" = "help"
"U" = "update"

######################
# Spotify-like Theme #
######################

[theme]
background = "#181818"
primary = "#F1F1F1"
secondary = "#DCDCDC"
title = "#1ED760"
playing = "#1ED760"
playing_selected = "#1ED760"
playing_bg = "#181818"
highlight = "#1DB954"
highlight_bg = "#000000"
error = "#FFE4E4"
error_bg = "#A50000"
statusbar = "#000000"
statusbar_progress = "#00AC4C"
statusbar_bg = "#00AC4C"
cmdline = "#CBFFDE"
cmdline_bg = "#444444"